name : workflow1
  

on :
  push:
    tags:
      - 'v*'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Créer et afficher var1
        run: |
          var1="Hello World"
          echo "var1: $var1"
        

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: failure() 
    steps:
      - name: Afficher un message de précision
        run: echo "Job1 a échoué, donc Job2 s'exécute."



















